export const produtos = [
  {
    id: "1",
    nome: "Brinco Diamante Trio",
    preco: "R$ 129,00",
    imagem: "/images/produtos/brinco-diamante.png",
    categoria: "Brincos",
    material: "Ouro 18k com zircônias",
    descricao: "Conjunto de três brincos com zircônias em ouro 18k, perfeito para múltiplas perfurações.",
  },
  {
    id: "2",
    nome: "Colar Pingente V Prata",
    preco: "R$ 159,00",
    imagem: "/images/produtos/colar-v-prata.png",
    categoria: "Colares",
    material: "Prata 925 com zircônias",
    descricao: "Colar delicado em prata 925 com pingente em formato V cravejado com zircônias.",
  },
  {
    id: "3",
    nome: "Brinco Coração Dourado",
    preco: "R$ 119,00",
    imagem: "/images/produtos/brinco-coracao.png",
    categoria: "Brincos",
    material: "Ouro 18k",
    descricao: "Par de brincos em formato de coração banhados a ouro 18k, design minimalista e elegante.",
  },
  {
    id: "4",
    nome: "Brinco Barras Douradas",
    preco: "R$ 129,00",
    imagem: "/images/produtos/brinco-barra-ouro.png",
    categoria: "Brincos",
    material: "Ouro 18k",
    descricao: "Conjunto de três brincos em formato de barra banhados a ouro 18k, perfeito para múltiplas perfurações.",
  },
  {
    id: "5",
    nome: "Brinco Barras Prateadas",
    preco: "R$ 119,90",
    imagem: "/images/produtos/brinco-barra-prata.png",
    categoria: "Brincos",
    material: "Prata 925",
    descricao: "Conjunto de três brincos em formato de barra em prata 925, design moderno e versátil.",
  },
  {
    id: "6",
    nome: "Brinco Argola Trançada",
    preco: "R$ 139,90",
    imagem: "/images/produtos/brinco-argola-ouro.png",
    categoria: "Brincos",
    material: "Ouro 18k",
    descricao: "Brinco de argola com design trançado banhado a ouro 18k, acompanha piercing de cartilagem.",
  },
  {
    id: "7",
    nome: "Colar V Cravejado",
    preco: "R$ 189,90",
    imagem: "/images/produtos/colar-v-diamante.png",
    categoria: "Colares",
    material: "Prata 925 com zircônias",
    descricao: "Colar em prata 925 com pingente em formato V totalmente cravejado com zircônias brilhantes.",
  },
  {
    id: "8",
    nome: "Colar Duplo Prata",
    preco: "R$ 169,90",
    imagem: "/images/produtos/colar-duplo-prata.png",
    categoria: "Colares",
    material: "Prata 925",
    descricao: "Conjunto de dois colares em prata 925, um modelo choker e outro com pingente personalizado.",
  },
  {
    id: "9",
    nome: "Colar Duplo Dourado",
    preco: "R$ 179,90",
    imagem: "/images/produtos/colar-duplo-ouro.png",
    categoria: "Colares",
    material: "Ouro 18k",
    descricao:
      "Conjunto de dois colares banhados a ouro 18k, um com pingentes em formato de moeda e outro estilo corrente.",
  },
  {
    id: "10",
    nome: "Colar Choker",
    preco: "R$ 149,90",
    imagem: "/placeholder.svg?height=500&width=500",
    categoria: "Colares",
    material: "Aço Inoxidável",
    descricao: "Colar choker minimalista em aço inoxidável.",
  },
  {
    id: "11",
    nome: "Brincos Pérola Clássico",
    preco: "R$ 139,90",
    imagem: "/placeholder.svg?height=500&width=500",
    categoria: "Brincos",
    material: "Prata 925 com Pérola",
    descricao: "Brincos clássicos com pérola em prata 925.",
  },
  {
    id: "12",
    nome: "Pulseira Corrente Fina",
    preco: "R$ 119,90",
    imagem: "/placeholder.svg?height=500&width=500",
    categoria: "Pulseiras",
    material: "Ouro 18k",
    descricao: "Pulseira de corrente fina banhada a ouro 18k.",
  },
]
